version: '3.8'
services:
  chat-api:
    build:
      context: ../chat-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatbot
      SPRING_DATASOURCE_USERNAME: chatbot
      SPRING_DATASOURCE_PASSWORD: chatbot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - qdrant
      - opensearch
  embeddings:
    build:
      context: ../embeddings-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot
    ports:
      - "5432:5432"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
    ports:
      - "9200:9200"
