name: Chat API CI

on:
  pull_request:
    paths:
      - 'chat-api/**'
      - '.github/workflows/app-ci.yml'
      - 'pom.xml'
  push:
    branches:
      - main
    paths:
      - 'chat-api/**'
      - '.github/workflows/app-ci.yml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Maven verify
        run: mvn -B -ntp verify
        working-directory: chat-api

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chat-api-test-reports
          path: chat-api/target/surefire-reports
          if-no-files-found: ignore
